service: print-pdf-server

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  profile: ${opt:profile, self:custom.defaultProfile}
  deploymentBucket: ${self:custom.config.environment.${self:provider.stage}.DEPLOYMENT_BUCKET}
  timeout: 60
  memorySize: 1024
  logRetentionInDays: 365

  environment:
    TZ: Asia/Tokyo
    HOME: /var/task

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::${self:custom.config.environment.${self:provider.stage}.PDF_BUCKET_NAME}/${self:custom.config.environment.${self:provider.stage}.PDF_BUCKET_KEY_PREFIX}/*

package:
  exclude:
    - docs/**
    - .eslintrc.json
    - .node-version
    - package-lock.json
    - README.md

functions:
  exportPdf:
    handler: src/handler.exportPdf
    environment:
      PDF_BUCKET_NAME: ${self:custom.config.environment.${self:provider.stage}.PDF_BUCKET_NAME}
      PDF_BUCKET_KEY_PREFIX: ${self:custom.config.environment.${self:provider.stage}.PDF_BUCKET_KEY_PREFIX}

plugins:
  - serverless-prune-plugin
  - serverless-plugin-include-dependencies

custom:
  defaultStage: stg
  defailtProfile: print-pdf-server

  config:
    environment:
      stg: ${file(./config/stg.yml)}
      prod: ${file(./config/prod.yml)}

  prune:
    automatic: true
    number: 3